<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="delivery_bot">

  <!-- Include macros -->
  <xacro:include filename="inertial_macros.xacro"/>

  <!-- Materials -->
  <material name="grey">
    <color rgba="0.5 0.5 0.5 1"/>
  </material>

  <material name="white">
    <color rgba="1 1 1 1"/>
  </material>

  <material name="red">
    <color rgba="1 0 0 1"/>
  </material>

  <material name="black">
    <color rgba="0 0 0 1"/>
  </material>

  <!-- Parameters -->
  <xacro:property name="body_length" value="0.26"/>
  <xacro:property name="body_width" value="0.22"/>
  <xacro:property name="body_height" value="0.203"/>
  <xacro:property name="wheel_to_body_bottom" value="0.01487"/>
  <xacro:property name="body_center_z" value="${wheel_to_body_bottom + body_height / 2}"/>
  <xacro:property name="wheel_radius" value="0.034"/>
  <xacro:property name="wheel_width" value="0.0256"/>
  <xacro:property name="body_mass" value="0.8"/>
  <xacro:property name="wheel_mass" value="0.1"/>
  <xacro:property name="material_density" value="1180" />



  <!-- Base link -->
  <link name="base_link" />

  <!-- Chassis joint -->
  <joint name="chassis_joint" type="fixed">
    <parent link="base_link"/>
    <child link="chassis"/>
    <origin xyz="0 0 0"/>
  </joint>

  <!-- Chassis link -->
  <link name="chassis">
    <visual>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="${body_length} ${body_width} ${body_height}" />
      </geometry>
      <material name="white" />
    </visual>
    <collision>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="${body_length} ${body_width} ${body_height}" />
      </geometry>
    </collision>
    <xacro:inertial_box mass="${body_mass}" x="${body_length}" y="${body_width}" z="${body_height}">
      <origin xyz="0 0 0" />
    </xacro:inertial_box>
  
  </link>

  <gazebo reference="chassis">
    <material>Gazebo/White</material>
    <mu1>0.1</mu1>
    <mu2>0.1</mu2>
  </gazebo>
  <!-- LEFT FRONT WHEEL LINK -->
  <joint name="left_front_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="left_front_wheel"/>
    <origin xyz="${body_length/2-1.2*wheel_radius} ${-body_width/2-wheel_width/2} ${-body_height/2}" rpy="-${pi/2} 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="left_front_wheel">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </collision>
    <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_width}" radius="${wheel_radius}">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:inertial_cylinder>
  </link>    

  <gazebo reference="left_front_wheel">
    <material>Gazebo/Black</material>
    <mu1>0.1</mu1>
    <mu2>0.1</mu2>
  </gazebo>


  <!-- RIGHT FRONT WHEEL LINK -->
  <joint name="right_front_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="right_front_wheel"/>
    <origin xyz="${body_length/2-1.2*wheel_radius} ${body_width/2+wheel_width/2} ${-body_height/2}" rpy="${pi/2} 0 0"/>
    <axis xyz="0 0 -1"/>
  </joint>

  <link name="right_front_wheel">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </collision>
     <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_width}" radius="${wheel_radius}">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:inertial_cylinder>
  </link>    

  <gazebo reference="right_front_wheel">
    <material>Gazebo/Black</material>
    <mu1>0.1</mu1>
    <mu2>0.1</mu2>
  </gazebo>


 <!-- LEFT REAR WHEEL LINK -->
  <joint name="left_rear_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="left_rear_wheel"/>
    <origin xyz="${-body_length/2+1.2*wheel_radius} ${-body_width/2-wheel_width/2} ${-body_height/2}" rpy="-${pi/2} 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="left_rear_wheel">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </collision>
     <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_width}" radius="${wheel_radius}">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:inertial_cylinder>
  </link>

  <gazebo reference="left_rear_wheel">
    <material>Gazebo/Black</material>
    <mu1>0.1</mu1>
    <mu2>0.1</mu2>

  </gazebo>    


  <!-- RIGHT REAR WHEEL LINK -->
  <joint name="right_rear_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="right_rear_wheel"/>
    <origin xyz="${-body_length/2+1.2*wheel_radius} ${body_width/2+wheel_width/2} ${-body_height/2}" rpy="${pi/2} 0 0"/>
    <axis xyz="0 0 -1"/>
  </joint>

  <link name="right_rear_wheel">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </collision>
     <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_width}" radius="${wheel_radius}">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:inertial_cylinder>
  </link>

  <gazebo reference="right_rear_wheel">
    <material>Gazebo/Black</material>
    <mu1>0.1</mu1>
    <mu2>0.1</mu2>
  </gazebo>    
  


</robot>
